Setup poetry
robota-suite/robota-core pull request #16
Opened 2024-05-20 18:44 UTC by Nigel007

Updated toml file to use poetry instead of setup tools. Created poetry lock file and removed requirements.txt as it is no longer required. Dependencies are now added using `poetry add <package-name>`. Dev specific dependencies can be added using the `--dev` flag before the package name. Ref: #14

2024-08-11 16:11 UTC, suzanneEmbury requested changes
This looks good, thanks.  Just a couple of queries to answer - no big changes required.

Overall, though, maybe this PR should include a small change to the README, to give instructions on how to build and publish the package using Poetry?  And also for installing Poetry if you are using the code base as a developer?  I checked out the PR to give it a try and found I did not have Poetry installed on this machine.  It's fairly obvious what the problem is but the developer experience might be a bit smoother if the need to install Poetry first is pointed out?

Thanks again!

2024-08-11 16:11 UTC, suzanneEmbury commented on pyproject.toml
> +authors = ["University of Manchester <suzanne.m.embury@manchester.ac.uk>"]
Thanks for streamlining the syntax here.  Do you know what the convention is for including authors/maintainers in the pyproject.toml file?  Should I be including everyone who has made a contribution through an accepted pull request?  I had a quick search for information but couldn't find anything.

2024-08-11 16:11 UTC, suzanneEmbury commented on pyproject.toml
> +[tool.poetry.dev-dependencies]
Can we set test code dependencies as well?  I have some tests that have not been copied across yet that use a mocking framework that would count as a test dependency.  Since we're leaving an empty dev-dependencies section in case some come up in future, should we have an empty test-dependencies section, too?  Or is that not supported by poetry at present?

2024-08-11 16:50 UTC, suzanneEmbury commented
Once this PR is merged, I'll make a new release with Poetry (instead of Twine) as an extra check that all is working well.

2024-08-12 21:41 UTC, nigelmj commented on pyproject.toml
> +authors = ["University of Manchester <suzanne.m.embury@manchester.ac.uk>"]
From my understanding, the authors list should only contain the people primarily responsible for the project's creation and ongoing development, not necessarily all contributors. I think they are usually recognised elsewhere, such as in a `CONTRIBUTORS.md` file or in the Contributors section under the Insights tab.

2024-08-12 21:50 UTC, nigelmj commented on pyproject.toml
> +[tool.poetry.dev-dependencies]
Yes! Poetry allows us to declare different dependency groups, so creating a separate section for test dependencies is [fully supported](https://python-poetry.org/docs/managing-dependencies/#:~:text=Poetry%20provides%20a%20way%20to,or%20to%20build%20the%20documentation.). I have updated the `pyproject.toml` file with an empty section for test dependencies to accommodate any future needs.

2024-08-12 21:53 UTC, nigelmj commented
The README has been updated with Poetry instructions and a test dependencies section has been added to the `pyproject.toml` file.

2024-08-12 22:11 UTC, suzanneEmbury commented on pyproject.toml
> +authors = ["University of Manchester <suzanne.m.embury@manchester.ac.uk>"]
Okay - thanks.  I'll go with that.  Good to know I don't need to remember to add something here every time I merge a PR.

2024-08-12 22:13 UTC, suzanneEmbury commented on pyproject.toml
> +[tool.poetry.dev-dependencies]
Thanks - good to have this here as a reminder.

2024-08-12 22:14 UTC, suzanneEmbury approved these changes
Thanks for making these tweaks.  This PR looks good now.

2024-08-12 22:24 UTC, suzanneEmbury commented
Erk ... I fixed the merge conflicts (since I had kept you waiting long enough on this) and now we're getting a CI error.

    E   ModuleNotFoundError: No module named 'loguru'

You've included loguru in the poetry dependencies, so I'm not sure what we've done here.

Are you able to take a further look, @nigelmj ?

2024-08-13 12:45 UTC, nigelmj commented
The CI pipeline and the migration to Poetry were done on different branches, which is why the pipeline still relied on the now-deleted requirements.txt. I've now updated the workflow file to run the tests through the virtual environment created with Poetry. Everything is working as expected now!

2024-08-14 17:14 UTC, suzanneEmbury commented
Thanks.  The tests also run with poetry in my development environment as well, now, following these same instructions.  So all looks good and I'm going to merge.

2024-08-14 17:15 UTC, merged